#!/usr/bin/env bash
# ============================================================
# ge-cli installer
# Usage: ./install.sh [--dry-run]
#
# Install methods:
#   1. Local:  ./install.sh        (from cloned repo)
#   2. Remote: bash <(curl -fsSL https://raw.githubusercontent.com/.../install.sh)
#
# What it does:
#   1. Clone repo to ~/.ge (if remote install)
#   2. Detect OS and shell
#   3. Inject eval "$(ge init <shell>)" into RC file
#   4. Initialize Git user account config file
# ============================================================

set -e

GE_REPO="https://github.com/isac7722/ge-cli.git"
GE_DEFAULT_DIR="$HOME/.ge"

# Detect if running from cloned repo or remote
GE_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"

if [[ -z "$GE_HOME" || ! -f "$GE_HOME/bin/ge" ]]; then
  echo ""
  echo "╔══════════════════════════════════════╗"
  echo "║       ge-cli Remote Install           ║"
  echo "╚══════════════════════════════════════╝"
  echo ""

  if [[ -d "$GE_DEFAULT_DIR/.git" ]]; then
    echo "  Existing ge-cli found: $GE_DEFAULT_DIR"
    echo "  Updating to latest version..."
    git -C "$GE_DEFAULT_DIR" pull --ff-only
  else
    echo "  Cloning repository: $GE_REPO"
    git clone "$GE_REPO" "$GE_DEFAULT_DIR"
  fi

  echo ""
  exec bash "$GE_DEFAULT_DIR/install.sh" "$@"
fi

DRY_RUN=false

# ── Option parsing ──────────────────────────────────────────

for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=true ;;
  esac
done

# ── Utility functions ───────────────────────────────────────

log()     { echo "  $1"; }
success() { echo "✔  $1"; }
warn()    { echo "⚠  $1"; }
error()   { echo "✗  $1"; exit 1; }
section() { echo ""; echo "── $1 ──────────────────────────────"; }

# ── Start ───────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════╗"
echo "║       ge-cli Installer                ║"
echo "╚══════════════════════════════════════╝"
$DRY_RUN && warn "DRY-RUN mode: no changes will be made"

# ── 1. Detect OS & Shell ──────────────────────────────────────

section "Detecting OS & Shell"

case "$(uname -s)" in
  Darwin*)
    OS="macOS"
    RC_FILE="$HOME/.zshrc"
    SHELL_TYPE="zsh"
    ;;
  Linux*)
    OS="Linux"
    if [[ -n "$ZSH_VERSION" ]] || [[ "$SHELL" == */zsh ]]; then
      RC_FILE="$HOME/.zshrc"
      SHELL_TYPE="zsh"
    else
      RC_FILE="$HOME/.bashrc"
      SHELL_TYPE="bash"
    fi
    ;;
  *)
    error "Unsupported OS: $(uname -s)"
    ;;
esac

success "Detected: $OS / $SHELL_TYPE → $RC_FILE"

# ── 2. Make bin/ge executable ─────────────────────────────────

chmod +x "$GE_HOME/bin/ge"

# ── 3. Add bin to PATH (if not already) ──────────────────────

section "PATH setup"

GE_BIN_DIR="$GE_HOME/bin"

if echo "$PATH" | tr ':' '\n' | grep -qx "$GE_BIN_DIR"; then
  success "bin/ge already in PATH"
else
  log "bin/ge will be available after shell integration"
fi

# ── 4. Inject shell integration into RC file ──────────────────

section "Shell integration ($RC_FILE)"

MARKER_START="# >>> ge-cli >>>"
MARKER_END="# <<< ge-cli <<<"

SOURCE_BLOCK="
${MARKER_START}
# ge-cli shell integration (generated by install.sh)
export GE_HOME=\"$GE_HOME\"
export PATH=\"\$GE_HOME/bin:\$PATH\"
eval \"\$(ge init $SHELL_TYPE)\"
${MARKER_END}"

# Also remove legacy gituser block if present
LEGACY_START="# >>> gituser >>>"
LEGACY_END="# <<< gituser <<<"

if grep -q "$MARKER_START" "$RC_FILE" 2>/dev/null; then
  success "Already integrated: $RC_FILE"
elif $DRY_RUN; then
  log "[dry-run] Source block will be added to $RC_FILE"
  log "[dry-run] Block contents:"
  echo "$SOURCE_BLOCK" | sed 's/^/    /'
else
  touch "$RC_FILE"

  # Remove legacy gituser block if present
  if grep -q "$LEGACY_START" "$RC_FILE" 2>/dev/null; then
    tmp_file="$(mktemp)"
    awk -v start="$LEGACY_START" -v end="$LEGACY_END" '
      $0 ~ start { skip=1; next }
      $0 ~ end   { skip=0; next }
      !skip { print }
    ' "$RC_FILE" > "$tmp_file"
    mv "$tmp_file" "$RC_FILE"
    log "Removed legacy gituser block"
  fi

  printf '%s\n' "$SOURCE_BLOCK" >> "$RC_FILE"
  success "Source block added: $RC_FILE"
fi

# ── 5. Initialize Git user config file ────────────────────────

section "Git User Config File"

GE_CONFIG_DIR="$HOME/.config/gituser"
GE_CONFIG="$GE_CONFIG_DIR/accounts"
GE_EXAMPLE="$GE_HOME/config/gitusers.example"

if [[ ! -f "$GE_CONFIG" ]]; then
  if $DRY_RUN; then
    log "[dry-run] Will create $GE_CONFIG"
    log "[dry-run] Template: $GE_EXAMPLE"
  else
    mkdir -p "$GE_CONFIG_DIR"
    cp "$GE_EXAMPLE" "$GE_CONFIG"
    success "Config file created: $GE_CONFIG"
    echo ""
    log "▶ Edit the file below to register your accounts:"
    log "     \$EDITOR $GE_CONFIG"
    log ""
    log "  Format:  aliases:name:email:~/.ssh/key_name"
    log "  Example: work,w:John:john@company.com:~/.ssh/work_ed25519"
  fi
else
  success "Config file already exists: $GE_CONFIG"
fi

# ── Done ────────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════╗"
echo "║       Installation Complete!          ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "  Apply changes immediately:"
echo "    source $RC_FILE"
echo ""
echo "  Usage:"
echo "    ge user list      # list accounts"
echo "    ge user <alias>   # switch account"
echo "    ge worktree add   # create worktree"
echo "    ge commit -m msg  # git passthrough"
echo ""
